Perform\RichContentBundle\Entity\Block:
    type: entity
    table: perform_rich_content_block
    repositoryClass: Perform\RichContentBundle\Repository\BlockRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        type:
            type: string
        value:
            type: json_array
        shared:
            type: boolean
        title:
            type: string
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
