services:
    perform_rich_content.block.text:
        public: false
        class: Perform\RichContentBundle\BlockType\TextBlockType
        tags:
            - {name: perform_rich_content.block_type, type: text}

    perform_rich_content.block.quote:
        public: false
        class: Perform\RichContentBundle\BlockType\QuoteBlockType
        tags:
            - {name: perform_rich_content.block_type, type: quote}

    perform_rich_content.block.video:
        public: false
        class: Perform\RichContentBundle\BlockType\VideoBlockType
        tags:
            - {name: perform_rich_content.block_type, type: video}

    perform_rich_content.block.image:
        public: false
        class: Perform\RichContentBundle\BlockType\ImageBlockType
        arguments:
            - '@perform_media.importer.file'
            - '@perform_media.repo.file'
        tags:
            - {name: perform_rich_content.block_type, type: image}
