services:
    perform_rich_content.block.text:
        public: false
        class: Perform\RichContentBundle\BlockType\TextBlockType
        tags:
            - {name: perform_rich_content.block_type, type: text}

    perform_rich_content.block.image:
        public: false
        class: Perform\RichContentBundle\BlockType\ImageBlockType
        tags:
            - {name: perform_rich_content.block_type, type: image}




            ## move
    perform_rich_content.type:
        class: Perform\RichContentBundle\Type\RichContentType
        arguments:
            - "@perform_base.asset_container"
        tags:
            - {name: perform_base.type, alias: rich_content}
